version: '3.7'

services:
  database_rentx:
    image: postgres
    container_name: rentx_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=rentx
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_rentx
    depends_on:
      - database_rentx

volumes:
  pgdata:
    driver: local
